CREATE TABLE JUGADOR (
	GAMERTAG VARCHAR(30) PRIMARY KEY,
	NOMBRE VARCHAR(30),
	EMAIL VARCHAR(30) UNIQUE, -- el correo es unico aunque un mismo jugador puede tener varios
	FECHA_NACIMIENTO DATE,
	PAIS_ORIGEN VARCHAR(30)
);

CREATE TABLE TORNEO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	FECHA_INICIO DATE, -- por torneos periodicos
	VIDEOJUEGO VARCHAR(30),
	FECHA_TERMINO DATE,
	POZO DECIMAL,
	MAX_EQUIPOS SMALLINT,
);

CREATE TABLE EQUIPO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	FECHA_CREACION DATE,
	CAPITAN VARCHAR(30), -- Ref a JUGADOR(gamertag)
	FOREIGN KEY (CAPITAN) REFERENCES JUGADOR (GAMERTAG) -- el capitan sera un jugador
);

CREATE TABLE SPONSOR (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	INDUSTRIA VARCHAR(30)
);

------------------------------------------------------ Relaciones ----------------------------------------------------------
CREATE TABLE ES_DEL_EQUIPO (
	GAMERTAG VARCHAR(30) PRIMARY KEY, -- Ref JUGADOR(gamertag)
	NOMBRE_EQUIPO VARCHAR(30), -- Ref EQUIPO(nombre)
	FOREIGN KEY (GAMERTAG) REFERENCES JUGADOR (GAMERTAG),
	FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO (NOMBRE)
);

CREATE TABLE ESTA_EN_TORNEO (
	NOMBRE_EQUIPO VARCHAR(30),
	NOMBRE_TORNEO VARCHAR(30),
	FECHA_INICIO_TORNEO DATE,
	PRIMARY KEY (NOMBRE_EQUIPO, NOMBRE_TORNEO, FECHA_INICIO_TORNEO),
	FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO (NOMBRE),
	FOREIGN KEY (NOMBRE_TORNEO, FECHA_INICIO_TORNEO) REFERENCES TORNEO (NOMBRE, FECHA_INICIO)
);

CREATE TABLE PARTIDA (
	"id" INT PRIMARY KEY,
	NOMBRE_TORNEO VARCHAR(30),
	FECHA_INICIO_TORNEO DATE,
	NOMBRE_EQUIPO1 VARCHAR(30),
	NOMBRE_EQUIPO2 VARCHAR(30),
	INICIO TIMESTAMP,
	PUNTAJE_EQUIPO1 SMALLINT,
	PUNTAJE_EQUIPO2 SMALLINT,
	FASE VARCHAR(30),
	FOREIGN KEY (NOMBRE_TORNEO, FECHA_INICIO_TORNEO) REFERENCES TORNEO (NOMBRE, FECHA_INICIO),
	FOREIGN KEY (NOMBRE_EQUIPO1) REFERENCES EQUIPO (NOMBRE),
	FOREIGN KEY (NOMBRE_EQUIPO2) REFERENCES EQUIPO (NOMBRE) --RESTRINGIR QUE NO SEA EL MISMO TEAM VS EL MISMO TEAM
);

CREATE TABLE ESTADISTICAS_EN_PARTIDA (
	GAMERTAG VARCHAR(30),
	ID_PARTIDA INT,
	KOS SMALLINT,
	RESTARTS SMALLINT,
	ASSISTS SMALLINT,
	PRIMARY KEY (GAMERTAG, ID_PARTIDA),
	FOREIGN KEY (GAMERTAG) REFERENCES JUGADOR (GAMERTAG),
	FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA ("id")
);

CREATE TABLE SPONSOR_DEL_TORNEO (
	NOMBRE_SPONSOR VARCHAR(30),
	NOMBRE_TORNEO VARCHAR(30),
	FECHA_INICIO_TORNEO DATE,
	MONTO INT, -- Mantenemos el monto en la relación, ya que depende del torneo específico
	PRIMARY KEY (NOMBRE_SPONSOR, NOMBRE_TORNEO, FECHA_INICIO_TORNEO),
	FOREIGN KEY (NOMBRE_SPONSOR) REFERENCES SPONSOR (NOMBRE),
	FOREIGN KEY (NOMBRE_TORNEO, FECHA_INICIO_TORNEO) REFERENCES TORNEO (NOMBRE, FECHA_INICIO)
);