-- 1. Eliminar tablas con el nivel de dependencia más profundo
--DROP TABLE ESTADISTICAS_EN_PARTIDA;

-- 2. Eliminar tablas que referencian a equipos, torneos y jugadores
--DROP TABLE PARTIDA;
--DROP TABLE ESTA_EN_TORNEO;
--DROP TABLE SPONSOR_DEL_TORNEO;
--DROP TABLE ES_DEL_EQUIPO;

-- 3. Eliminar entidad Equipo (debe ir antes de Jugador porque referencia al Capitán)
--DROP TABLE EQUIPO;

-- 4. Eliminar entidades base (sin dependencias foráneas activas tras los drops anteriores)
--DROP TABLE JUGADOR;
--DROP TABLE TORNEO;
--DROP TABLE SPONSOR;

CREATE TABLE JUGADOR (
	GAMERTAG VARCHAR(30) PRIMARY KEY,
	NOMBRE VARCHAR(30),
	EMAIL VARCHAR(30) UNIQUE, -- el correo es unico aunque un mismo jugador puede tener varios
	FECHA_NACIMIENTO DATE,
	PAIS_ORIGEN VARCHAR(30)
);

CREATE TABLE TORNEO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	VIDEOJUEGO VARCHAR(30),
	FECHA_INICIO DATE,
	FECHA_TERMINO DATE,
	POZO DECIMAL(10, 2),
	MAX_EQUIPOS SMALLINT
);

CREATE TABLE EQUIPO (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	FECHA_CREACION DATE,
	CAPITAN VARCHAR(30), -- Ref a JUGADOR(gamertag)
	FOREIGN KEY (CAPITAN) REFERENCES JUGADOR (GAMERTAG) -- el capitan sera un jugador
);

CREATE TABLE SPONSOR (
	NOMBRE VARCHAR(30) PRIMARY KEY,
	INDUSTRIA VARCHAR(30)
);

------------------------------------------------------ Relaciones ----------------------------------------------------------
CREATE TABLE ES_DEL_EQUIPO (
	GAMERTAG VARCHAR(30) PRIMARY KEY, -- Ref JUGADOR(gamertag)
	NOMBRE_EQUIPO VARCHAR(30), -- Ref EQUIPO(nombre)
	FOREIGN KEY (GAMERTAG) REFERENCES JUGADOR (GAMERTAG),
	FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO (NOMBRE)
);

CREATE TABLE ESTA_EN_TORNEO (
	NOMBRE_EQUIPO VARCHAR(30),
	NOMBRE_TORNEO VARCHAR(30),
	PRIMARY KEY (NOMBRE_EQUIPO, NOMBRE_TORNEO),
	FOREIGN KEY (NOMBRE_EQUIPO) REFERENCES EQUIPO (NOMBRE),
	FOREIGN KEY (NOMBRE_TORNEO) REFERENCES TORNEO (NOMBRE)
);

CREATE TABLE PARTIDA (
	"id" INT PRIMARY KEY,
	NOMBRE_TORNEO VARCHAR(30),
	NOMBRE_EQUIPO1 VARCHAR(30),
	NOMBRE_EQUIPO2 VARCHAR(30),
	INICIO TIMESTAMP,
	PUNTAJE_EQUIPO1 SMALLINT,
	PUNTAJE_EQUIPO2 SMALLINT,
	FASE VARCHAR(30),
	FOREIGN KEY (NOMBRE_TORNEO) REFERENCES TORNEO (NOMBRE),
	FOREIGN KEY (NOMBRE_EQUIPO1) REFERENCES EQUIPO (NOMBRE),
	FOREIGN KEY (NOMBRE_EQUIPO2) REFERENCES EQUIPO (NOMBRE) --RESTRINGIR QUE NO SEA EL MISMO TEAM VS EL MISMO TEAM
);

CREATE TABLE ESTADISTICAS_EN_PARTIDA (
	GAMERTAG VARCHAR(30),
	ID_PARTIDA INT,
	KOS SMALLINT,
	RESTARTS SMALLINT,
	ASSISTS SMALLINT,
	PRIMARY KEY (GAMERTAG, ID_PARTIDA),
	FOREIGN KEY (GAMERTAG) REFERENCES JUGADOR (GAMERTAG),
	FOREIGN KEY (ID_PARTIDA) REFERENCES PARTIDA ("id")
);

CREATE TABLE SPONSOR_DEL_TORNEO (
	NOMBRE_SPONSOR VARCHAR(30),
	NOMBRE_TORNEO VARCHAR(30),
	MONTO INT, -- Mantenemos el monto en la relación, ya que depende del torneo específico
	PRIMARY KEY (NOMBRE_SPONSOR, NOMBRE_TORNEO),
	FOREIGN KEY (NOMBRE_SPONSOR) REFERENCES SPONSOR (NOMBRE),
	FOREIGN KEY (NOMBRE_TORNEO) REFERENCES TORNEO (NOMBRE)
);